### ISSUE TITLE
Error: Cannot allocate memory

### ISSUE THREAD

**Issue by nathanmlim** [chemprop/chemprop#18] opened 2020-03-04 21:17 UTC
I've been trying to train a model with a dataset size of approximately 1.4 million entries (attached)
[full_smi+act-fix.csv.tar.gz](https://github.com/chemprop/chemprop/files/4289721/full_smi%2Bact-fix.csv.tar.gz)

Running using the GPU version of pytorch, I ran the command  `python train.py --data_path DUDE/full_smi+act-fix.csv --dataset_type regression --save_dir DUDE/full-gpu_checkpoints --seed 0 --use_compound_names --split_type random --num_folds=3 --quiet --batch_size 5000`

But this results in the error below:

```
  File "train.py", line 11, in <module>
    cross_validate(args, logger)
  File "/data/nlim/Github/chemprop/chemprop/train/cross_validate.py", line 29, in cross_validate
    model_scores = run_training(args, logger)
  File "/data/nlim/Github/chemprop/chemprop/train/run_training.py", line 196, in run_training
    writer=writer
  File "/data/nlim/Github/chemprop/chemprop/train/train.py", line 72, in train
    preds = model(batch, features_batch)
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/nlim/Github/chemprop/chemprop/models/model.py", line 88, in forward
    output = self.ffn(self.encoder(*input))
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/nlim/Github/chemprop/chemprop/models/mpn.py", line 185, in forward
    batch = mol2graph(batch, self.args)
  File "/data/nlim/Github/chemprop/chemprop/features/featurization.py", line 319, in mol2graph
    return BatchMolGraph(mol_graphs, args)
  File "/data/nlim/Github/chemprop/chemprop/features/featurization.py", line 251, in __init__
    self.f_bonds = torch.FloatTensor(f_bonds)
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 181230420 bytes. Error code 12 (Cannot allocate memory)
```

Does this indicate that I am running out of memory?

**Comment by swansonk14** [comment] 2020-04-08 20:09
Hi @nathanmlim, thank you for your question! A few people have run into this problem when training with very large datasets. The issue is that we have a caching mechanism which saves the mapping from SMILES to preprocessed molecular graph, but this cache takes up a huge amount of memory for large datasets. But without the cache, training is 30-40% slower due to the time it takes to redo the preprocessing on every epoch.

Fortunately, I finally had time to improve the caching mechanism. I've altered the mechanism so that it now only uses caching for datasets with <= 10,000 molecules and instead employs PyTorch's DataLoader to perform parallelized preprocessing (without caching) of molecules for larger datasets. This should mean that you can train on 1.4 million molecules without any memory issues and without a meaningful slowdown.

The new code is currently in this PR https://github.com/chemprop/chemprop/pull/27 but will be merged into master soon. The new parallel data loading will happen automatically for large datasets so you don't have to do anything to enable it.

Also I noticed that you're using the `--use_compound_names` flag. In the new version of the code, I've removed that flag and in its place added two new flags: `--smiles_column <column>` and `--target_columns <column_1> <column_2> ...`. These allow you to select the columns which contain SMILES and the columns which contain the targets while ignoring all other columns.

**Closed by swansonk14** 2020-04-08 20:09 UTC

**Comment by nathanmlim** [comment] 2020-04-15 20:53
@swansonk14 Does the entire dataset need to still fit into the system RAM? I've tested out the new changes to master and my chemprop processes still seem to die when working with large datasets.
