### ISSUE TITLE
[Feature Request] Multi-GPU Training

### ISSUE THREAD

**Issue by nathanmlim** [chemprop/chemprop#17] opened 2020-02-27 20:19 UTC
Would it be possible to implement a way to do multi-GPU training via PyTorch? The tutorials on the [PyTorch](https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html) website make it appear easy to do so. I think it would be useful for speeding up training with larger datasets.

[DataParallel Docs](https://pytorch.org/docs/stable/nn.html#dataparallel)

**Comment by nathanmlim** [comment] 2020-02-27 20:37
Just tried doing this by replacing this line 157  in `chemprop.train.run_training.py` [here](https://github.com/chemprop/chemprop/blob/350534437b8c273e428441d48fb9cf9e820f6d5a/chemprop/train/run_training.py#L157) like so

```
import torch.nn as nn
...
else: 
    debug(f'Building model {model_idx}')
    if torch.cuda.device_count() > 1:
        debug(f'#Lets use {torch.cuda.device_count()} GPUs')
        model = build_model(args)
        model = nn.DataParallel(model, dim=0)
```

But this results in an error related to the call to `loss_func(pred,targets)` where the shape of the output: `pred`  always appears to be the number of GPUs * batch_size where the `targets` has the shape equal to batch_size.

```
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cross_validate(args, logger)
  File "/data/nlim/Github/chemprop/chemprop/train/cross_validate.py", line 29, in cross_validate
    model_scores = run_training(args, logger)
  File "/data/nlim/Github/chemprop/chemprop/train/run_training.py", line 196, in run_training
    writer=writer
  File "/data/nlim/Github/chemprop/chemprop/train/train.py", line 79, in train
    loss = loss_func(preds, targets) * class_weights * mask
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 431, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/site-packages/torch/nn/functional.py", line 2215, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/site-packages/torch/functional.py", line 52, in broadcast_tensors
    return torch._C._VariableFunctions.broadcast_tensors(tensors)
RuntimeError: The size of tensor a (60) must match the size of tensor b (30) at non-singleton dimension 0
```

**Comment by swansonk14** [comment] 2020-04-08 20:13
Hi @nathanmlim, thank you for the request and thank you for experimenting with DataParallel! However, I believe the memory issue is actually due to overloaded system RAM rather than GPU RAM. The problem is a caching mechanism we use to map SMILES to preprocessed molecular graphs, which takes up a huge amount of system RAM for large datasets. I have now switched over to using PyTorch's DataLoader, which can perform this preprocessing parallel, thereby eliminating the need for caching for large datasets. This feature is currently implemented in this PR https://github.com/chemprop/chemprop/pull/27 but will be merged into master soon.

**Closed by swansonk14** 2020-04-08 20:13 UTC
