### ISSUE TITLE
[QUESTION]: Inference using GPU

### ISSUE THREAD

**Issue by Kaixiong-Zhou** [chemprop/chemprop#576] opened 2024-01-09 19:11 UTC
It seems when using chemprop_predict, the model is not loaded into gpu and the inference is conducted sample by sample in cpu. The hyper of batch_size and gpu cannot be manipulated in prediction phase.

**Comment by kevingreenman** [comment] 2024-01-10 22:14
Can you confirm whether you're able to train on a GPU? If you're not able to train or predict on a GPU, there is likely something wrong with your environment (e.g. you have a CPU-only version of PyTorch installed). If the issue is only with prediction, I'm not sure why that would be happening. 

What do you mean by "The hyper of batch_size and gpu cannot be manipulated in prediction phase."?

Regardless, CPU inference should also be pretty fast. Our [benchmark](https://pubs.acs.org/doi/10.1021/acs.jcim.3c01250) showed that you could do inference for 100k molecules on a laptop CPU in less than 2 minutes.

**Comment by JacksonBurns** [comment] 2024-02-02 16:37
If this issue persists, please feel free to re-open this issue. Closing for now.

**Closed by JacksonBurns** 2024-02-02 16:37 UTC
Labels: question
