### ISSUE TITLE
Error with rdkit_2d_normalized 

### ISSUE THREAD

**Issue by matany58** [chemprop/chemprop#104] opened 2020-10-31 13:59 UTC
I used rdkit_2d_normalized  to train the model as stated below
python train.py --data_path  tox21/tox21.csv --dataset_type classification --split_type scaffold_balanced --num_folds 5 --extra_metrics {prc-auc,accuracy}   --features_generator rdkit_2d_normalized --no_features_scaling   --save_dir 
tox21/tox21_checkpointsmato

I received the error below;

features_batch = torch.from_numpy(np.stack(features_batch)).float().to(self.device)
  File "<__array_function__ internals>", line 6, in stack
TypeError: dispatcher for __array_function__ did not return an iterable
Please how do you resolve this error

**Comment by dmoccia** [comment] 2020-11-04 21:14
Not 100% on this one @matany58 but I think you need to pass extra_metrics as a list so

`python train.py --data_path tox21/tox21.csv --dataset_type classification --split_type scaffold_balanced --num_folds 5 --extra_metrics prc-auc accuracy --features_generator rdkit_2d_normalized --no_features_scaling --save_dir
tox21/tox21_checkpointsmato`

Essentially a spaced list after the --extra_metrics param as explained in the tap docs

https://github.com/swansonk14/typed-argument-parser#list

Let me know if this helps

**Comment by matany58** [comment] 2020-11-05 00:27
dmoccia, thanks for your response but it did not resolve the issue. Also I I removed the extra_metrics but it is not resolve it

**Comment by dmoccia** [comment] 2020-11-05 20:29
@matany58,  sorry slow to reply but I wanted to test what you were trying.   I have run the following (not too completion but seemed to work ok):

`chemprop_train --data_path data/tox21.csv --dataset_type classification --split_type scaffold_balanced --num_folds 5 --extra_metrics prc-auc accuracy --features_generator rdkit_2d_normalized --no_features_scaling --save_dir tox21/tox21_checkpoints/`

after installing chemprop in the following manner:

`conda create -n chemprop_new python=3.8
conda activate chemprop_new
conda install -c conda-forge rdkit
pip install git+https://github.com/bp-kelley/descriptastorus
pip install chemprop`

Can you let me know which version of chemprop you are using?  Is it this latest release?  Also I am assuming the tox21.csv dataset you are using the one packaged in the data folder with chemprop and not your own dataset? 

Do you see any output prior to this error? Such as something like the following?

![image](https://user-images.githubusercontent.com/362618/98292138-3c1df700-1f7a-11eb-9ea3-c0fd9b410fb5.png)

I believe the error you are receiving is related to the use of rdkit_2d_normalized features which may be empty given the details of the error

**Comment by matany58** [comment] 2020-11-06 15:23
Hello dmoccia 

You need to run the program to completion to notice the error. The program run past the stage you stated.   I am using chemprop version 1.0.3b0 and python version: Python 3.7.8 Also how is rdkit_2d_normalized features and how do you address it. I still getting the error below;
 features_batch = torch.from_numpy(np.stack(features_batch)).float().to(self.device)
  File "<__array_function__ internals>", line 6, in stack
TypeError: dispatcher for __array_function__ did not return an iterable

**Comment by matany58** [comment] 2020-11-06 15:25
Also ,yes I used the tox21.csv dataset,  one packaged in the data folder with chemprop and not my data set

**Comment by hmmm7** [comment] 2020-12-04 08:36
> @ matany58，很抱歉回复缓慢，但我想测试一下您在尝试什么。我已经运行了以下命令（不是很完整，但是看起来还可以）：
> 
> `chemprop_train --data_path data/tox21.csv --dataset_type classification --split_type scaffold_balanced --num_folds 5 --extra_metrics prc-auc accuracy --features_generator rdkit_2d_normalized --no_features_scaling --save_dir tox21/tox21_checkpoints/`
> 
> 按照以下方式安装chemprop之后：
> 
> `conda create -n chemprop_new python=3.8 conda activate chemprop_new conda install -c conda-forge rdkit pip install git+https://github.com/bp-kelley/descriptastorus pip install chemprop`
> 
> 您能告诉我您使用的是哪个版本的chemprop吗？这是最新版本吗？另外我假设您使用的是tox21.csv数据集，它与chemprop一起打包在data文件夹中，而不是您自己的数据集？
> 
> 在此错误之前，您是否看到任何输出？如下面的东西？
> 
> ![图片](https://user-images.githubusercontent.com/362618/98292138-3c1df700-1f7a-11eb-9ea3-c0fd9b410fb5.png)
> 
> 我相信您收到的错误与rdkit_2d_normalized功能的使用有关，鉴于错误的详细信息，这些功能可能为空



> @matany58, sorry slow to reply but I wanted to test what you were trying. I have run the following (not too completion but seemed to work ok):
> 
> `chemprop_train --data_path data/tox21.csv --dataset_type classification --split_type scaffold_balanced --num_folds 5 --extra_metrics prc-auc accuracy --features_generator rdkit_2d_normalized --no_features_scaling --save_dir tox21/tox21_checkpoints/`
> 
> after installing chemprop in the following manner:
> 
> `conda create -n chemprop_new python=3.8 conda activate chemprop_new conda install -c conda-forge rdkit pip install git+https://github.com/bp-kelley/descriptastorus pip install chemprop`
> 
> Can you let me know which version of chemprop you are using? Is it this latest release? Also I am assuming the tox21.csv dataset you are using the one packaged in the data folder with chemprop and not your own dataset?
> 
> Do you see any output prior to this error? Such as something like the following?
> 
> ![image](https://user-images.githubusercontent.com/362618/98292138-3c1df700-1f7a-11eb-9ea3-c0fd9b410fb5.png)
> 
> I believe the error you are receiving is related to the use of rdkit_2d_normalized features which may be empty given the details of the error

I meet the problem like the picture,plz help me to deal it.Thanks!!!!
![warnings](https://user-images.githubusercontent.com/67692386/101141113-cbd4c500-364e-11eb-9c3e-85ace9f22697.jpg)

**Comment by hesther** [comment] 2021-04-02 20:33
Dear @matany58, dear @hmmm7, were your problems actually resolved?

@hmmm7, it is usually better to open a new issue than commenting on an existing one. In this case, your comment slipped our notice, sorry! What exactly is the error you are experiencing? The output looks ok to me. The tox21 dataset has a bunch of protons, which cause the "WARNING not removing hydrogen atom without neighbours" warning (a warning by RDKit, which is nothing to worry about). Let me know if there is still an issue, and I will try and fix it/help you through it.

@matany58, if your problem was not resolved, could you copy and paste the full output that running your command produces? It seems like there is an error in the feature generator, which might be caused by how descriptastorus was installed. I just ran your command to completion, without any error.

Regarding your question on features, and how they are normalized: The rdkit_2d_normalized features are described in detail in the Chemprop paper ([ARXIV-version](https://arxiv.org/pdf/1904.01561.pdf) or [published version ](https://pubs.acs.org/doi/abs/10.1021/acs.jcim.9b00237)). In short, they are 200 molecular rdkit descriptors which were prenormalized by fitting to cumulative density functions on a dataset of 100k diverse molecules.

**Comment by hesther** [comment] 2021-04-16 21:21
Closing this issue, since it seems to be resolved - @hmmm7 and @matany58 please feel free to reopen or post a new issue if further assistance is required!

**Closed by hesther** 2021-04-16 21:21 UTC
