### ISSUE TITLE
[v2 QUESTION]: invalid choice for molecule-featurizers

### ISSUE THREAD

**Issue by xiongguoli** [chemprop/chemprop#1046] opened 2024-10-08 13:59 UTC
I wanted to concatenate v1_rdkit_2d_normalized with molecule graph as the molecule representation, however, it showed " invalid choice:  'v1_rdkit_2d_normalized' (choose from 'morgan_binary', morgan_count'). It seems that not all the featurizers described in the document are supported in CLI, or maybe I missed some key points?

**Comment by JacksonBurns** [comment] 2024-10-08 14:19
Duplicate of https://github.com/chemprop/chemprop/issues/1026

@xiongguoli if you installed with `pip` you are probably on ChemProp 2.0.4 - this version does not yet support this featurizer, but it will be available in 2.0.5 which should be released in the near future.

**Comment by JacksonBurns** [comment] 2024-10-08 14:20
If you want to use it now, install from `main`.

**Closed by JacksonBurns** 2024-10-08 14:19 UTC
Labels: question

**Comment by xiongguoli** [comment] 2024-10-08 14:34
> If you want to use it now, install from `main`.

ok，i will try it, thanks~

**Comment by xiongguoli** [comment] 2024-10-08 15:33
> If you want to use it now, install from `main`.

I have tried to install chemprop from source using pip and then pass the ‘ v1_rdkit_2d_normalized’ parameter. However, it showed "DEPRECATION WARNING: Please use MorganGenerator"

**Comment by xiongguoli** [comment] 2024-10-09 02:40
> The underlying featurizer `descripastorus` uses deprecated RDKit syntax. You can ignore that, or downgrade your version of RDKit to make it go away.

Another question is Molecule-Level 2D Features like morgan_binary and v1_rdkit_2d_normalized are used before message passing or after message passing, They are called features or descriptors in different paragraphs, so I am a little confused about whether use "concatenated vector" to describe this integration.

**Comment by JacksonBurns** [comment] 2024-10-09 14:14
They are concatenated to the learned representation, so they come after message passing. You can't message pass molecular-level features.

They are 'interchangeably' called features and descriptors because they mean different things. Anything you concatenate to the learned representation is a feature, but if it's specifically something like molecular weight which is known in cheminformatics as a _descriptor_, then we refer to the feature as descriptors.
