### ISSUE TITLE
Features for the antibiotics checkpoints

### ISSUE THREAD

**Issue by miquelduranfrigola** [chemprop/chemprop#108] opened 2020-11-04 19:13 UTC
Hi,

I want to make predictions using the Antibiotics checkpoints provided here: http://chemprop.csail.mit.edu/checkpoints

I do this by running the following command:
```
chemprop_predict --test_path data/smiles.csv --checkpoint_dir checkpoint --preds_path test_preds.csv --features_generator rdkit_2d_normalized --no_features_scaling
```

Am I using the correct features generator for this checkpoint?

In addition, when running predictions, I get the following warning:
```
Warning: Pretrained parameter "encoder.encoder.cached_zero_vector" cannot be found in model parameters.                                   
Warning: Pretrained parameter "encoder.encoder.W_i.weight" cannot be found in model parameters.
Warning: Pretrained parameter "encoder.encoder.W_h.weight" cannot be found in model parameters.
Warning: Pretrained parameter "encoder.encoder.W_o.weight" cannot be found in model parameters.
Warning: Pretrained parameter "encoder.encoder.W_o.bias" cannot be found in model parameters.
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
```
I wonder if this something I should be worried about.

Thanks!

M

**Comment by Shredderroy** [comment] 2021-03-18 19:55
I am experiencing the same problem. Is there a location from where the file for features_path can be downloaded?

**Comment by hesther** [comment] 2021-04-02 21:19
Dear @miquelduranfrigola, dear @Shredderroy, sorry for getting back to you so late. I have not been on the antibiotics project, but hope to help you nevertheless. There are a number of issues you are addressing:

We cannot provide the file for features_path directly, since the features depend on your input csv. So depending on the molecules you want to compute predictions on, the features will be different each time! BUT, you can create the features file yourself, via one of the utility scripts in the `scripts` folder. Based on your nomenclature (data being read from a file `data/smiles.csv`), you could do:

` python scripts/save_features.py --data_path data/smiles.csv --save_path data/smiles_features.npz --features_generator rdkit_2d_normalized`
 
 which will precompute features specific to the provided input molecules, and saves them to `data/smiles_features.npz`. Now, you can run

`python predict.py --test_path data/smiles.csv --checkpoint_dir checkpoint --preds_path test_preds.csv --features_path  data/smiles_features.npz`

And the predictions should run fine (at least they do on my system, newest version of chemprop). That being said, the warnings you are seeing are VERY concerning (The "pretained parameter...cannot be found"), and I wonder whether you correctly downloaded all checkpoint files. There should be 20 files ending with `pt` in the checkpoint folder you are loading the models from. Maybe redownload the files and make sure to use the newest chemprop version.

Now, the only thing I am not sure about is whether `--features_generator rdkit_2d_normalized` was used for features, or `--features_generator rdkit_2d`. I could not tell from the paper, unfortunately, but can ask others who might know. The checkpoint files have a flag attached to them that the input features were scaled (again) - so I would slightly tend towards the non-normalized features, but it might just be that the normalized features were used and normalized again.

**Comment by Shredderroy** [comment] 2021-04-06 16:36
Hi @hesther , thank you very much for your response.

I have indeed downloaded the 20 checkpoints correctly. And I can confirm that the `features_generator` was not `rdkit_2d_normalized`. I will try again with `rdkit_2d` as the `features_generator`, and report how it went.

Once again, thank you for your help.

**Comment by hesther** [comment] 2021-04-12 23:35
Hi @Shredderroy, I spoke with one of the authors of the paper. They used `rdkit_2d_normalized` - please thus don't use `rdkit_2d`, I assumed that wrong, I apologise! 

Also, if you use a newish version of Chemprop, the warning about not being able to load the pertained parameters (which @miquelduranfrigola reported) should not show up anymore, that was fixed some time ago. 

I seem to have found a small bug though with how checkpoints are read. If you run the commands exactly as I posted them, it should work correctly, but I will look into this more, and possibly post an update/bugfix soon.

**Comment by Shredderroy** [comment] 2021-04-22 18:56
Hi @hesther , thank you again for your time.

The only way that I could make chemprop run for me was by making the following edits to the chemprop/chemprop/utils.py:

```
if train_args.features_scaling != predict_args.features_scaling:
    pass
```

and

```
if validate_feature_sources:
    pass
```

Then I tested the output against the predictions returned by the chemprop web interface. And they match perfectly.

The trouble is that I am not trying to submit a million molecules in one large batch. I have actually written a programme that calls a chemprop-trained model for each molecule that it creates and evaluates during its run. So I have to run chemprop in a server that listens on a TCP port and returns a prediction whenever a SMILES is submitted to it.

**Comment by hesther** [comment] 2021-04-22 19:36
You are welcome. Chemprop currently requires the features to be made in the exact same way as in a checkpoint, and the antibiotics checkpoint were made by reading features from a file. If you instead want to generate them on the fly (although they were read from file during training), which seems to make sense in your case where you pass SMILES to an already loaded model, the check that you pointed out (`if train_args.features_scaling != predict_args.features_scaling:`) raises a ValueError, which you omitted by the changes you posted. As long as you only use it in this way (being sure about creating the exact same features), that is okay. We will include a bugfix for the inconsistency in reading checkpoints soon (that is, that you currently cannot supply the no_feature_scaling option);, and I am thinking about supplying an option that omits all the feature safety checks (for cases just as yours) - but until then, your current workflow is legit.

Is there anything else I can help with?

**Comment by hesther** [comment] 2021-04-26 17:35
We just fixed the features scaling bug. You should now be able to run:

`python scripts/save_features.py --data_path data/smiles.csv --save_path data/smiles_features.npz --features_generator rdkit_2d_normalized`

`python predict.py --test_path data/smiles.csv --checkpoint_dir checkpoint --preds_path test_preds.csv --features_path data/smiles_features.npz --no_features_scaling`

(This will produce the exact same predictions you had before, the only difference is that you can correctly set the `--no_features_scaling` option now).

**Comment by hesther** [comment] 2021-04-26 19:05
I will close this issue since I hope the problem was solved - feel free to reopen if anything else comes up, or open a new issue!

**Comment by miquelduranfrigola** [comment] 2021-04-28 11:53
Hi @hesther thanks for your help. Greatly appreciated.

I have tried your code (save_features + predict) using chemprop==1.3.0 and **halicin** as input: C1=C(SC(=N1)SC2=NN=C(S2)N)[N+](=O)[O-]
Checkpoints were downloaded from your repository: https://drive.google.com/file/d/1odxgoR_iXGLPMX1b8tueyMWpSB1d8R-v/view?usp=sharing

So I run these commands:

```
python scripts/save_features.py --data_path data.csv --save_path features.npz --features_generator rdkit_2d_normalized
python predict.py --test_path data.csv --checkpoint_dir 0405_broad_inhibition_20folds --preds_path pred.csv --features_path features.npz --no_features_scaling
```

When running prediction, I get warnings all the time, of the sort:
```
WARNING:root:No normalization for BCUT2D_MWLOW
WARNING:root:No normalization for BCUT2D_CHGHI
WARNING:root:No normalization for BCUT2D_CHGLO
WARNING:root:No normalization for BCUT2D_LOGPHI
WARNING:root:No normalization for BCUT2D_LOGPLOW
```

I assume is fine. However, I would like to be 100% sure. I am doubtful because, when I use your predict web app for halicin, I always get:
* SMILES: C1=C(SC(=N1)SC2=NN=C(S2)N)[N+](=O)[O-]
* 50uM_Inhibition: 0.9193356320261955

Whereas in my case I get variable results, ranging from 0.88 to 0.92, depending on the run. Is this expected?

Many thanks in advance!

**Comment by hesther** [comment] 2021-04-28 14:02
Hi @miquelduranfrigola, the warnings (no normalisation for...) stem from the third-party package descriptastorus, over which we unfortunately have no control. However, they do not cause any error/difference to previous versions (descriptastorus creates the 200 rdkit features). That said, there is definitely something wrong with getting variable results upon each run. A forward pass through the network is deterministic, and results in the exact same prediction no matter how often you compute it. I just ran predictions on halicin multiple times, using both the checkpoints from the csail website, and from google drive, and always get the exact same prediction of 0.9193356320261955 each run, which is in line with the website. 

I used the following data.csv, and the exact same commands as in your comment:
```
smiles
C1=C(SC(=N1)SC2=NN=C(S2)N)[N+](=O)[O-]
```
Which python version and OS are you on? I will try to reproduce the error.

**Comment by miquelduranfrigola** [comment] 2021-04-28 16:22
Hi @hesther I have to apologize it was an issue on my end: I was using a non-standard smiles representation for halicin non-consistently. When I use this smiles string C1=C(SC(=N1)SC2=NN=C(S2)N)[N+](=O)[O-] indeed I get the right prediction 0.9193356320261955. So all good! Many thanks and my apologies.

**Comment by hesther** [comment] 2021-04-28 16:24
@miquelduranfrigola - no worries at all, am happy that it all works now. This also reminded me that I wanted to write a bug report to the descriptastorus team regarding all the warning, which I now finally did - thanks for the reminder!

**Closed by hesther** 2021-04-28 16:24 UTC
