### ISSUE TITLE
Behavior of forward step in MPN module seems inconsistent for Smiles vs BatchMolGraph input

### ISSUE THREAD

**Issue by beazerj** [chemprop/chemprop#153] opened 2021-03-15 16:01 UTC
This issue references the MPN class: https://github.com/chemprop/chemprop/blob/22a89849a953673c7d3bbfbffb426e2879599128/chemprop/models/mpn.py#L153

The code suggests that `batch` should have the same length as `self.encoder` which is `args.number_of_molecules`. 

If i pass in a list of smiles, `batch` is created by iterating over itself and passing each inner list of smiles to `mol2graph` -> https://github.com/chemprop/chemprop/blob/22a89849a953673c7d3bbfbffb426e2879599128/chemprop/models/mpn.py#L211 

Given the above, the result is expected to have len `args.number_of_molecules` which would imply that the len of batch had to originally be args.number_of_molecules (and the len of inner list would be the number of datapoints). 

However this line -> https://github.com/chemprop/chemprop/blob/22a89849a953673c7d3bbfbffb426e2879599128/chemprop/models/mpn.py#L207 checks the len of the inner list for args.number_of_molecules.

It seems that instead of `if len(batch[0]) > 1:`, this should be `if len(batch) > 1` as it is here: https://github.com/chemprop/chemprop/blob/22a89849a953673c7d3bbfbffb426e2879599128/chemprop/models/mpn.py#L234

A short note in the documentation or comment in the code to indicate the meaning of each dimension could be helpful.

**Comment by hesther** [comment] 2021-03-15 17:17
Dear @beazerj, I agree, the outer list is of length `args.number_of_molecules`, whereas the inner list holds the different datapoints (if applicable, i.e. for a list of SMILES or list of RDKit molecules). If a list of BatchMolGraph is supplied, it is kept as is (it already has the correct dimensions). Thus, I think `if len(batch[0]) > 1:` on line 207 (and 216) are a bug. I today merged a bug fix for the type annotation in the forward pass (see #151), which is a related issue. I will run some tests to make sure this is the intended behavior and fix this soon, as well as add a note about the dimensions in the docstring of `forward`. Thank you very much for reporting!

**Closed** 2021-03-24 18:54 UTC
