### ISSUE TITLE
Code fails to run when executed outside of install dir

### ISSUE THREAD

**Issue by JamesALumley** [chemprop/chemprop#63] opened 2020-07-22 19:06 UTC
[ERROR] subprocess.CalledProcessError: Command '['git', 'remote', 'get-url', 'origin']' returned non-zero exit status 129.

This problem persists for me even when I run the code from the install directory.  Others have referenced a fix running the code from within the dir but this failed with the same error.  There is a simple work around, commenting out line 46 from chemprop/chemprop/train/run_training.py and then code runs to completion with no errors.

 41     # Print args
 42     debug('Args')
 43     debug(args)
 44
 45     # Save args ****Comment this out****
 46     #args.save(os.path.join(args.save_dir, 'args.json'))
 47
 48     # Set pytorch seed for random initial weights
 49     torch.manual_seed(args.pytorch_seed)
 50

Running the git config command within the install dir does return the repo correctly.
userid@login chemprop]$ git config --get remote.origin.url
https://github.com/chemprop/chemprop.git

Typically, you would not run the code from in the directory it is installed in and would instead run from a separate model build directory so seems like a fix is needed?

Full trace below:

Traceback (most recent call last):
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/site-packages/tap/utils.py", line 66, in get_git_url
    url = check_output(['git', 'remote', 'get-url', 'origin'])
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/site-packages/tap/utils.py", line 33, in check_output
    output = subprocess.check_output(command, stderr=devnull).decode('utf-8').strip()
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'remote', 'get-url', 'origin']' returned non-zero exit status 129.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 7, in <module>
    chemprop_train()
  File "/hpc/scratch/userid/builds/chemprop/chemprop/utils.py", line 376, in wrap
    result = func(*args, **kwargs)
  File "/hpc/scratch/userid/builds/chemprop/chemprop/train/cross_validate.py", line 95, in chemprop_train
    cross_validate(args=args, logger=logger)
  File "/hpc/scratch/userid/builds/chemprop/chemprop/train/cross_validate.py", line 48, in cross_validate
    model_scores = run_training(args, logger)
  File "/hpc/scratch/userid/builds/chemprop/chemprop/train/run_training.py", line 47, in run_training
    args.save(os.path.join(args.save_dir, 'args.json'))
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/site-packages/tap/tap.py", line 501, in save
    args = self._log_all() if with_reproducibility else self.as_dict()
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/site-packages/tap/tap.py", line 292, in _log_all
    arg_log['reproducibility'] = self.get_reproducibility_info()
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/site-packages/tap/tap.py", line 281, in get_reproducibility_info
    reproducibility['git_url'] = get_git_url(commit_hash=True)
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/site-packages/tap/utils.py", line 69, in get_git_url
    url = check_output(['git' 'config' '--get' 'remote.origin.url'])
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/site-packages/tap/utils.py", line 33, in check_output
    output = subprocess.check_output(command, stderr=devnull).decode('utf-8').strip()
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gitconfig--getremote.origin.url': 'gitconfig--getremote.origin.url'
(my-rdkit-env) [userid@login1 chemprop]$

_Originally posted by @JamesALumley in https://github.com/chemprop/chemprop/issues/28#issuecomment-662628103_

**Comment by apdff** [comment] 2020-07-24 18:06
I had the same issue. This appears to be a problem with tap (typed-argument-parser). By default, when a tap object is saved, it also saves "reproducibility" data which contains a git url for the code being run. Based on the fix that the OP of the previous issue report found, my guess is that this is a parameter that can be called with the updated git, but tap is expecting that the git information is available in the current directory, not the directory the code is located in.

So when 'args' (which is a Tap object) is saved on line 46 of chemprop/train/run_training.py, it fails because tap can't find the git url. You can comment out the save on line 46 as you suggested. Or if you want to save the arguments used in evaluation (and don't care about tap's reproducibility info), you can pass an additional argument to save, like so:

    args.save(os.path.join(args.save_dir, 'args.json'), with_reproducibility=False)

This has worked just fine for me without errors and you can still run chemprop from other directories while saving all inputs.

**Comment by jasonzdeng** [comment] 2020-07-27 16:21
Thanks for sharing the solutions, as I ran into the same issue with the latest pull. Could this be somehow fixed in the next update?

**Comment by swansonk14** [comment] 2020-09-10 13:38
Hi @JamesALumley, thank you for reporting the issue! And thank you @apdff, who correctly identified the problem as an issue in Tap. If you update Tap to the latest version (1.5.4) and add the `with_reproducibility=False`, then that should fix the issue. If you're still running into any problems, please let me know.

**Closed by swansonk14** 2020-09-10 13:38 UTC
